### ISSUE TITLE
Offer the project as saas?

### ISSUE THREAD

**Issue by Shahin-rmz** [astronuttt/twitter2telegram#1]
As Twitter getting more popularity as the richest person on earth wants (or at least shows that he wants) to acquire it, it will be good idea to make this project more accessible for people. 
It would be good idea to provide this project as saas.

**Comment by astronuttt** [comment]
I made this for a project and now that it's done, I don't even need it anymore. I just put it in here as an example for Tweepy maybe.

It's good to mention that Twitter's API is now more restricted and the chance to get into the developer program is very low.
